/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.kostrowski.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Thor extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 343424005315934881L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Thor\",\"namespace\":\"pl.kostrowski.avro\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"surname\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"birthDate\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}},{\"name\":\"skills\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ThorSkills\",\"fields\":[{\"name\":\"skillName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"skillDescription\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"skillDate\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}},{\"name\":\"skillCost\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\",\"java-class\":\"java.math.BigDecimal\"}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
  }

  private static final BinaryMessageEncoder<Thor> ENCODER =
      new BinaryMessageEncoder<Thor>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Thor> DECODER =
      new BinaryMessageDecoder<Thor>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Thor> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Thor> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Thor> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Thor>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Thor to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Thor from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Thor instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Thor fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String name;
   private java.lang.String surname;
   private java.time.LocalDate birthDate;
   private java.util.List<pl.kostrowski.avro.ThorSkills> skills;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Thor() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param surname The new value for surname
   * @param birthDate The new value for birthDate
   * @param skills The new value for skills
   */
  public Thor(java.lang.String name, java.lang.String surname, java.time.LocalDate birthDate, java.util.List<pl.kostrowski.avro.ThorSkills> skills) {
    this.name = name;
    this.surname = surname;
    this.birthDate = birthDate;
    this.skills = skills;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return surname;
    case 2: return birthDate;
    case 3: return skills;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.data.TimeConversions.DateConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = value$ != null ? value$.toString() : null; break;
    case 1: surname = value$ != null ? value$.toString() : null; break;
    case 2: birthDate = (java.time.LocalDate)value$; break;
    case 3: skills = (java.util.List<pl.kostrowski.avro.ThorSkills>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'surname' field.
   * @return The value of the 'surname' field.
   */
  public java.lang.String getSurname() {
    return surname;
  }


  /**
   * Sets the value of the 'surname' field.
   * @param value the value to set.
   */
  public void setSurname(java.lang.String value) {
    this.surname = value;
  }

  /**
   * Gets the value of the 'birthDate' field.
   * @return The value of the 'birthDate' field.
   */
  public java.time.LocalDate getBirthDate() {
    return birthDate;
  }


  /**
   * Sets the value of the 'birthDate' field.
   * @param value the value to set.
   */
  public void setBirthDate(java.time.LocalDate value) {
    this.birthDate = value;
  }

  /**
   * Gets the value of the 'skills' field.
   * @return The value of the 'skills' field.
   */
  public java.util.List<pl.kostrowski.avro.ThorSkills> getSkills() {
    return skills;
  }


  /**
   * Sets the value of the 'skills' field.
   * @param value the value to set.
   */
  public void setSkills(java.util.List<pl.kostrowski.avro.ThorSkills> value) {
    this.skills = value;
  }

  /**
   * Creates a new Thor RecordBuilder.
   * @return A new Thor RecordBuilder
   */
  public static pl.kostrowski.avro.Thor.Builder newBuilder() {
    return new pl.kostrowski.avro.Thor.Builder();
  }

  /**
   * Creates a new Thor RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Thor RecordBuilder
   */
  public static pl.kostrowski.avro.Thor.Builder newBuilder(pl.kostrowski.avro.Thor.Builder other) {
    if (other == null) {
      return new pl.kostrowski.avro.Thor.Builder();
    } else {
      return new pl.kostrowski.avro.Thor.Builder(other);
    }
  }

  /**
   * Creates a new Thor RecordBuilder by copying an existing Thor instance.
   * @param other The existing instance to copy.
   * @return A new Thor RecordBuilder
   */
  public static pl.kostrowski.avro.Thor.Builder newBuilder(pl.kostrowski.avro.Thor other) {
    if (other == null) {
      return new pl.kostrowski.avro.Thor.Builder();
    } else {
      return new pl.kostrowski.avro.Thor.Builder(other);
    }
  }

  /**
   * RecordBuilder for Thor instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Thor>
    implements org.apache.avro.data.RecordBuilder<Thor> {

    private java.lang.String name;
    private java.lang.String surname;
    private java.time.LocalDate birthDate;
    private java.util.List<pl.kostrowski.avro.ThorSkills> skills;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pl.kostrowski.avro.Thor.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.surname)) {
        this.surname = data().deepCopy(fields()[1].schema(), other.surname);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.birthDate)) {
        this.birthDate = data().deepCopy(fields()[2].schema(), other.birthDate);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.skills)) {
        this.skills = data().deepCopy(fields()[3].schema(), other.skills);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Thor instance
     * @param other The existing instance to copy.
     */
    private Builder(pl.kostrowski.avro.Thor other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.surname)) {
        this.surname = data().deepCopy(fields()[1].schema(), other.surname);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.birthDate)) {
        this.birthDate = data().deepCopy(fields()[2].schema(), other.birthDate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.skills)) {
        this.skills = data().deepCopy(fields()[3].schema(), other.skills);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public pl.kostrowski.avro.Thor.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public pl.kostrowski.avro.Thor.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'surname' field.
      * @return The value.
      */
    public java.lang.String getSurname() {
      return surname;
    }


    /**
      * Sets the value of the 'surname' field.
      * @param value The value of 'surname'.
      * @return This builder.
      */
    public pl.kostrowski.avro.Thor.Builder setSurname(java.lang.String value) {
      validate(fields()[1], value);
      this.surname = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'surname' field has been set.
      * @return True if the 'surname' field has been set, false otherwise.
      */
    public boolean hasSurname() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'surname' field.
      * @return This builder.
      */
    public pl.kostrowski.avro.Thor.Builder clearSurname() {
      surname = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'birthDate' field.
      * @return The value.
      */
    public java.time.LocalDate getBirthDate() {
      return birthDate;
    }


    /**
      * Sets the value of the 'birthDate' field.
      * @param value The value of 'birthDate'.
      * @return This builder.
      */
    public pl.kostrowski.avro.Thor.Builder setBirthDate(java.time.LocalDate value) {
      validate(fields()[2], value);
      this.birthDate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'birthDate' field has been set.
      * @return True if the 'birthDate' field has been set, false otherwise.
      */
    public boolean hasBirthDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'birthDate' field.
      * @return This builder.
      */
    public pl.kostrowski.avro.Thor.Builder clearBirthDate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'skills' field.
      * @return The value.
      */
    public java.util.List<pl.kostrowski.avro.ThorSkills> getSkills() {
      return skills;
    }


    /**
      * Sets the value of the 'skills' field.
      * @param value The value of 'skills'.
      * @return This builder.
      */
    public pl.kostrowski.avro.Thor.Builder setSkills(java.util.List<pl.kostrowski.avro.ThorSkills> value) {
      validate(fields()[3], value);
      this.skills = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'skills' field has been set.
      * @return True if the 'skills' field has been set, false otherwise.
      */
    public boolean hasSkills() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'skills' field.
      * @return This builder.
      */
    public pl.kostrowski.avro.Thor.Builder clearSkills() {
      skills = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Thor build() {
      try {
        Thor record = new Thor();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.surname = fieldSetFlags()[1] ? this.surname : (java.lang.String) defaultValue(fields()[1]);
        record.birthDate = fieldSetFlags()[2] ? this.birthDate : (java.time.LocalDate) defaultValue(fields()[2]);
        record.skills = fieldSetFlags()[3] ? this.skills : (java.util.List<pl.kostrowski.avro.ThorSkills>) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Thor>
    WRITER$ = (org.apache.avro.io.DatumWriter<Thor>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Thor>
    READER$ = (org.apache.avro.io.DatumReader<Thor>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










